export const USER_FORM_WEIGHT_CHANGED = 'USER_FORM_WEIGHT_CHANGED';
export const USER_FORM_AGE_CHANGED = 'USER_FORM_AGE_CHANGED';
export const USER_FORM_HEIGHT_CHANGED = 'USER_FORM_HEIGHT_CHANGED';
export const USER_FORM_GENDER_CHANGED = 'USER_FORM_GENDER_CHANGED';
export const USER_FORM_ACTIVITY_CHANGED = 'USER_FORM_ACTIVITY_CHANGED';
export const USER_DATA_CHANGED = 'USER_DATA_CHANGED';