export const USER_WEIGHT_CHANGED = 'USER_WEIGHT_CHANGED';
export const USER_AGE_CHANGED = 'USER_AGE_CHANGED';
export const USER_HEIGHT_CHANGED = 'USER_HEIGHT_CHANGED';
export const USER_GENDER_CHANGED = 'USER_GENDER_CHANGED';
export const USER_ACTIVITY_CHANGED = 'USER_ACTIVITY_CHANGED';
export const USER_DATA_CHANGED = 'USER_DATA_CHANGED';